tasks:
  - init: |
      sh -c "$(curl -sSfL https://s3.amazonaws.com/release.renec.foundation/v1.9.29/install)"
      export PATH="/home/gitpod/.local/share/renec/install/active_release/bin:$PATH"
      eval $(gp env -e PATH=$HOME/.local/share/renec/install/active_release/bin:$PATH)
      npm install
      npm run build:program-rust
    command: |
      gp open README-gitpod.md
      renec-keygen new --no-bip39-passphrase -o keypair.json
      renec config set --keypair keypair.json
      renec config set --url localhost
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
ports:
  - port: 1024
    onOpen: ignore
  - port: 8899
    onOpen: ignore
  - port: 8900
    onOpen: ignore
  - port: 9900
    onOpen: ignore
