name: Hello Example
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - run: |
          rustup install stable
          cargo --version
          docker --version
      - run: >-
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: >-
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
      - run: |
          sudo apt-get update
          sudo apt-get install -y openssl --allow-unauthenticated
          sudo apt-get install -y libssl-dev --allow-unauthenticated
          sudo apt-get install -y clang-7 --allow-unauthenticated
          sudo apt-get install -y libssl1.1 --allow-unauthenticated
          clang-7 --version
          npm install node
          node --version
          npm install
          sh -c "$(curl -sSfL https://s3.amazonaws.com/release.renec.foundation/v1.9.29/install)"
          export PATH=~/.local/share/renec/install/active_release/bin:$PATH
          renec-install info
          renec-keygen new --no-bip39-passphrase
          renec-test-validator --quiet &
          npm run lint
          npm run build:program-rust
          npm run test:program-rust
          cargo test-bpf --manifest-path=./src/program-rust/Cargo.toml
          renec config set --url http://127.0.0.1:8899
          renec program deploy dist/program/helloworld.so
          npm run start
          npm run build:program-c
          renec program deploy dist/program/helloworld.so
          npm run start
